services:
  app:
    build:
      context: .
    depends_on:
        - db
    ports:
      - "${DOCKER_HOST_BACKEND_PORT}:8080"
    environment:
      - OPENAPI_API_KEY=${OPENAPI_API_KEY}
      - DATABASE_HOST=${DATABASE_HOST}
  db:
    image: postgres:15.3
    ports:
      - "${DOCKER_HOST_DB_PORT}:5432"
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
volumes:
  db:
